name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Build all formats
        run: npm run build
        
      - name: Create release artifacts directory
        run: mkdir -p release-artifacts
        
      - name: Copy standalone builds to release artifacts
        run: |
          cp dist/standalone/lcp-performance-tracer.js release-artifacts/
          cp dist/standalone/lcp-performance-tracer.min.js release-artifacts/
          cp dist/standalone/lcp-performance-tracer.js.map release-artifacts/
          cp dist/standalone/lcp-performance-tracer.min.js.map release-artifacts/
          
      - name: Create checksums
        run: |
          cd release-artifacts
          sha256sum *.js *.map > checksums.txt
          
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## Standalone JavaScript Build
            
            This release includes standalone JavaScript bundles that can be used directly in browsers without any build tools.
            
            ### Files
            - `lcp-performance-tracer.js` - Development build with source maps
            - `lcp-performance-tracer.min.js` - Production build (minified) with source maps
            
            ### Usage
            
            Include in your HTML:
            ```html
            <script src="https://github.com/Azumaxoid/nr-browser-resource-tracer/releases/download/${{ steps.get_version.outputs.VERSION }}/lcp-performance-tracer.min.js"></script>
            ```
            
            Then use the global `LCPPerformanceTracer` object:
            ```javascript
            const tracer = new LCPPerformanceTracer.LCPPerformanceTracer({
              newRelicAccountId: 'your-account-id',
              newRelicInsertKey: 'your-insert-key'
            });
            tracer.start();
            ```
            
            ### Checksums
            SHA256 checksums are available in `checksums.txt`
            
          files: |
            release-artifacts/lcp-performance-tracer.js
            release-artifacts/lcp-performance-tracer.min.js
            release-artifacts/lcp-performance-tracer.js.map
            release-artifacts/lcp-performance-tracer.min.js.map
            release-artifacts/checksums.txt
          draft: false
          prerelease: false
          
  publish-npm:
    runs-on: ubuntu-latest
    needs: build-and-release
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build library
        run: npm run build
        
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}